# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ..reports import ICPlot


def test_ICPlot_inputs():
    input_map = dict(
        in_ICs=dict(
            extensions=None,
            mandatory=True,
        ),
        in_file=dict(
            extensions=None,
            mandatory=True,
        ),
        in_mask=dict(
            extensions=None,
        ),
        in_ts=dict(
            extensions=None,
            mandatory=True,
        ),
        out_report=dict(
            extensions=None,
            hash_files=False,
            usedefault=True,
        ),
    )
    inputs = ICPlot.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value


def test_ICPlot_outputs():
    output_map = dict(
        out_report=dict(
            extensions=None,
        ),
    )
    outputs = ICPlot.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
