# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ..nilearn import Smooth


def test_Smooth_inputs():
    input_map = dict(
        fwhm=dict(
            usedefault=True,
        ),
        input_image=dict(
            mandatory=True,
        ),
        out_postfix=dict(
            usedefault=True,
        ),
        output_image=dict(
            genfile=True,
            hash_files=False,
        ),
    )
    inputs = Smooth.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value


def test_Smooth_outputs():
    output_map = dict(
        output_image=dict(),
    )
    outputs = Smooth.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
