# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ..confounds import GatherConfounds


def test_GatherConfounds_inputs():
    input_map = dict(
        acompcor=dict(
            extensions=None,
        ),
        confounds_file=dict(
            extensions=None,
        ),
        crowncompcor=dict(
            extensions=None,
        ),
        ic_roi_signals=dict(
            extensions=None,
        ),
        region_signals=dict(
            extensions=None,
        ),
        tcompcor=dict(
            extensions=None,
        ),
    )
    inputs = GatherConfounds.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value


def test_GatherConfounds_outputs():
    output_map = dict(
        confounds_file=dict(
            description="Confounds from fmriprep and confounds from roi",
            extensions=None,
        ),
        confounds_list=dict(),
    )
    outputs = GatherConfounds.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
