# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ..bids import BIDSDerivativeDataGrabber


def test_BIDSDerivativeDataGrabber_inputs():
    input_map = dict(
        anat_derivatives=dict(),
        bold_derivatives=dict(),
        subject_id=dict(),
    )
    inputs = BIDSDerivativeDataGrabber.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value


def test_BIDSDerivativeDataGrabber_outputs():
    output_map = dict(
        anat2std_xfm=dict(),
        anat_ribbon=dict(),
        bold_t1=dict(),
        boldmask_t1=dict(),
        boldref_t1=dict(),
        confounds_file=dict(),
        confounds_metadata=dict(),
        fsnative2t1w_xfm=dict(),
        morphometrics=dict(),
        out_dict=dict(),
        std2anat_xfm=dict(),
        std_aparc=dict(),
        std_aseg=dict(),
        std_dseg=dict(),
        std_mask=dict(),
        std_preproc=dict(),
        std_tpms=dict(),
        surfaces=dict(),
        t1w2fsnative_xfm=dict(),
        t1w_aparc=dict(),
        t1w_aseg=dict(),
        t1w_dseg=dict(),
        t1w_mask=dict(),
        t1w_preproc=dict(),
        t1w_tpms=dict(),
        template=dict(),
    )
    outputs = BIDSDerivativeDataGrabber.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
