# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ..nilearn import Connectivity


def test_Connectivity_inputs():
    input_map = dict(
        atlas=dict(
            mandatory=True,
        ),
        brain_mask=dict(),
        conn_measure=dict(
            usedefault=True,
        ),
        input_image=dict(
            mandatory=True,
        ),
        output_image=dict(
            genfile=True,
            hash_files=False,
        ),
    )
    inputs = Connectivity.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value


def test_Connectivity_outputs():
    output_map = dict(
        output_conn=dict(
            mandatory=True,
        ),
    )
    outputs = Connectivity.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
