# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ..confounds import SelectConfounds


def test_SelectConfounds_inputs():
    input_map = dict(
        confounds=dict(
            exist=True,
            extensions=None,
            mandatory=True,
        ),
        confounds_metadata=dict(
            exist=True,
            extensions=None,
            mandatory=True,
        ),
        confounds_spec=dict(
            mandatory=True,
        ),
        demean=dict(
            usedefault=True,
        ),
        output_dir=dict(),
        pipeline=dict(
            mandatory=True,
        ),
    )
    inputs = SelectConfounds.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value


def test_SelectConfounds_outputs():
    output_map = dict(
        sample_mask=dict(),
        selected_confounds=dict(
            extensions=None,
        ),
    )
    outputs = SelectConfounds.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
