# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ..nilearn import Denoise


def test_Denoise_inputs():
    input_map = dict(
        confounds_file=dict(
            mandatory=True,
        ),
        input_image=dict(
            mandatory=True,
        ),
        mask_img=dict(),
        out_postfix=dict(
            usedefault=True,
        ),
        output_image=dict(
            genfile=True,
            hash_files=False,
        ),
        pipeline=dict(),
        tr=dict(),
    )
    inputs = Denoise.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value


def test_Denoise_outputs():
    output_map = dict(
        output_image=dict(),
    )
    outputs = Denoise.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
