# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ..nilearn import CanICAInterface


def test_CanICAInterface_inputs():
    input_map = dict(
        algorithm=dict(),
        confounds=dict(),
        in_files=dict(),
        mask=dict(),
        n_components=dict(
            usedefault=True,
        ),
    )
    inputs = CanICAInterface.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value


def test_CanICAInterface_outputs():
    output_map = dict(
        components_img=dict(),
        components_img_zscored=dict(),
        metadata_file=dict(),
        ts=dict(),
    )
    outputs = CanICAInterface.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
