# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ..confounds import ROIcomp


def test_ROIcomp_inputs():
    input_map = dict(
        IC_components=dict(
            extensions=None,
        ),
        ROI_mask=dict(
            extensions=None,
        ),
        threshold=dict(
            usedefault=True,
        ),
        ts=dict(
            extensions=None,
        ),
    )
    inputs = ROIcomp.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value


def test_ROIcomp_outputs():
    output_map = dict(
        metadata_file=dict(
            description="Text file containing component metadata",
            extensions=None,
        ),
        out_signal=dict(),
    )
    outputs = ROIcomp.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
