# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ..confounds import LesionMasks


def test_LesionMasks_inputs():
    input_map = dict(
        in_file=dict(
            extensions=None,
        ),
        roi_file=dict(
            extensions=None,
        ),
    )
    inputs = LesionMasks.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value


def test_LesionMasks_outputs():
    output_map = dict(
        out_masks=dict(),
    )
    outputs = LesionMasks.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
