# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ..pyants import ApplyTransforms


def test_ApplyTransforms_inputs():
    input_map = dict(
        default_value=dict(
            usedefault=True,
        ),
        imagetype=dict(
            usedefault=True,
        ),
        input_image=dict(
            extensions=None,
            mandatory=True,
        ),
        interpolation=dict(
            argstr="%s",
            usedefault=True,
        ),
        out_postfix=dict(
            usedefault=True,
        ),
        output_image=dict(
            genfile=True,
            hash_files=False,
        ),
        reference_image=dict(
            extensions=None,
            mandatory=True,
        ),
        transforms=dict(
            argstr="%s",
            mandatory=True,
        ),
    )
    inputs = ApplyTransforms.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value


def test_ApplyTransforms_outputs():
    output_map = dict(
        output_image=dict(
            extensions=None,
        ),
    )
    outputs = ApplyTransforms.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
