# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ..reports import RegisterLesionRPT


def test_RegisterLesionRPT_inputs():
    input_map = dict(
        compress_report=dict(
            usedefault=True,
        ),
        moving_image=dict(
            extensions=None,
            mandatory=True,
        ),
        out_report=dict(
            extensions=None,
            hash_files=False,
            usedefault=True,
        ),
        reference_file=dict(
            extensions=None,
            mandatory=True,
        ),
        roi=dict(
            extensions=None,
        ),
    )
    inputs = RegisterLesionRPT.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value


def test_RegisterLesionRPT_outputs():
    output_map = dict(
        out_report=dict(
            extensions=None,
        ),
    )
    outputs = RegisterLesionRPT.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
