# AUTO-GENERATED by tools/checkspecs.py - DO NOT EDIT
from ..reports import SessionSummary


def test_SessionSummary_inputs():
    input_map = dict(
        bold_t1=dict(),
        croprun=dict(),
    )
    inputs = SessionSummary.input_spec()

    for key, metadata in list(input_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(inputs.traits()[key], metakey) == value


def test_SessionSummary_outputs():
    output_map = dict(
        out_report=dict(
            extensions=None,
        ),
    )
    outputs = SessionSummary.output_spec()

    for key, metadata in list(output_map.items()):
        for metakey, value in list(metadata.items()):
            assert getattr(outputs.traits()[key], metakey) == value
