# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pytest

on:
  push:
    branches: [ 'minor_issues', 'main' ]
  pull_request:
    branches: [ 'develop', 'main' ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    env:
      MPLBACKEND: Agg

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version:
          -3.10
          -3.9
          -3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        pip install -r requirements-test.txt
        pip install -e .[testing]
    - name: Test with pytest
      run: |
        pytest
